//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5420
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TestSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TestSchema.xsd", IsNullable=false)]
public partial class group {

	private string xmlstringField;

	private string adminIDField;

	private groupParam[] paramField;

	/// <remarks/>
	public string xmlstring {
		get {
			return this.xmlstringField;
		}
		set {
			this.xmlstringField = value;
		}
	}

	/// <remarks/>
	public string adminID {
		get {
			return this.adminIDField;
		}
		set {
			this.adminIDField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("param")]
	public groupParam[] param {
		get {
			return this.paramField;
		}
		set {
			this.paramField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TestSchema.xsd")]
public partial class groupParam {

	private string keyField;

	private string valueField;

	/// <remarks/>
	public string key {
		get {
			return this.keyField;
		}
		set {
			this.keyField = value;
		}
	}

	/// <remarks/>
	public string value {
		get {
			return this.valueField;
		}
		set {
			this.valueField = value;
		}
	}
}
